name: Opcode Is Synced

on:
  push:
    branches:
      - '*'
    paths:
      - 'src/instructions.*'
      - 'opcodes.yaml'
  workflow_dispatch:

jobs:
  opcode-is-synced:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Install yq
        run: |
          pip3 install --user yq
          curl -L 'https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64' > $HOME/.local/bin/jq
          chmod +x $HOME/.local/bin/jq
      - name: Regenerate the opcodes
        run: |
          PATH="$HOME/.local/bin:$PATH" bash ./tools/opcode_generator
      - name: Compile generated code
        run: gcc -c src/instructions.c
      - name: Fail if not up-to-date
        run: git status | grep clean